### ISSUE TITLE
Have you code processed IEMOCAP dataset to 2 folder wav and txt ?

### ISSUE THREAD

**Issue by trungtruc123** [lessonxmk/Bimodal-ER#1]
wavs = glob.glob('e:/test/iemocap/*.wav')
   transes = glob.glob('e:/test/iemo_t/trans/*.txt')

Please help me

**Comment by lessonxmk** [comment]
The wav files are processed and renamed by https://github.com/lessonxmk/head_fusion/handleIEMOCAP.py

The txt files are provided by IEMOCAP data set and we put them into one independent folder. 
For convenience, we just uploaded  "IEMO_T.zip". It contains the txt folder.

**Comment by trungtruc123** [comment]
import shutil
import glob
import os
source_dir ='/content/drive/MyDrive/DATN/multimodal-speech-emotion-recognition/data/IEMOCAP_full_release/*/sentences/wav/*'
dest_dir ='/content/drive/MyDrive/DATN/Test/Wavs'
count =0
for filename in glob.glob(os.path.join(source_dir, 'S*.wav')):
    shutil.copy(filename, dest_dir)
    count +=1
print('count:', count)
I coded above to collect all file wav in 5 session.

**Comment by trungtruc123** [comment]
thanks you
